name: gtk-blackhat                                                                                                                               
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - openai
  - plotly
  - scikit-learn
  - scipy
  - statsmodels
  - pip
  
  